# Generated by Django 4.0.3 on 2022-03-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='auth.group')),
            ],
            options={
                'verbose_name': 'Доступная ссылка',
                'verbose_name_plural': 'Доступные ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
