# Generated by Django 4.0.3 on 2022-03-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urls',
            new_name='url',
        ),
    ]
