# Generated by Django 4.0.3 on 2022-03-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_alter_url_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['title'], 'verbose_name': 'URL', 'verbose_name_plural': 'URL'},
        ),
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='url',
            name='members',
        ),
        migrations.CreateModel(
            name='PermGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Группа')),
                ('urls', models.ManyToManyField(blank=True, related_name='members', to='main.url')),
            ],
            options={
                'verbose_name': 'Доступные ссылки',
                'verbose_name_plural': 'Доступные ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
