# Generated by Django 4.0.3 on 2022-03-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_url_options_rename_url_url_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermGroup',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
