# Generated by Django 4.0.3 on 2022-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-created_at'], 'verbose_name': 'URL', 'verbose_name_plural': 'Разграничение доступа к URL'},
        ),
        migrations.RemoveField(
            model_name='url',
            name='group',
        ),
        migrations.AddField(
            model_name='url',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
