# Generated by Django 4.0.3 on 2022-03-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_url_options_remove_url_group_url_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'Разграничение доступа к URL'},
        ),
        migrations.RenameField(
            model_name='url',
            old_name='urls',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
    ]
