# Generated by Django 4.0.3 on 2022-03-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_url_options_rename_urls_url_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='users',
            new_name='members',
        ),
    ]
